export const initial_Movies = [
  {
    id: "100",
    name: "Life Of Pi",
    pic: "https://m.media-amazon.com/images/I/81URWoj3hdL._AC_SL1500_.jpg",
    des: "Pi Patel finds a way to survive in a lifeboat that is adrift in the middle of nowhere. His fight against the odds is heightened by the company of a hyena and a male Bengal tiger.",
    rating: "8.1",
    trailer: "https://www.youtube.com/embed/3mMN693-F3U",
  },
  {
    id: "101",
    name: "M.S. Dhoni",
    pic: "https://m.media-amazon.com/images/M/MV5BZjAzZjZiMmQtMDZmOC00NjVmLTkyNTItOGI2Mzg4NTBhZTA1XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg",
    des: "M S Dhoni, a boy from Ranchi, aspires to play cricket for India. Though he initially tries to please his father by working for the Indian Railways, he ultimately decides to chase his dreams.",
    rating: "7.9",
    trailer: "https://www.youtube.com/embed/6L6XqWoS8tw",
  },
  {
    id: "102",
    name: "The Walk",
    pic: "https://images-na.ssl-images-amazon.com/images/I/81iXs0dZn2L.jpg",
    des: "Philippe Petit, a French street performer, dreams of performing daring stunts. He attempts to walk between the Twin Towers of the World Trade Center in New York on a tightrope.",
    rating: "7.9",
    trailer: "https://www.youtube.com/embed/GR1EmTKAWIw",
  },
  {
    id: "103",
    name: "Avengers: Endgame",
    pic: "https://images.moviesanywhere.com/4677177f6f0595289bc3e767e7b47459/1d6c6c73-ab1e-4453-969c-6a4e965ebb37.jpg",
    rating: "8.4",
    des: "On the lush alien world of Pandora live the Na'vi, beings who appear primitive but are highly evolved. Because the planet's environment is poisonous, human/Na'vi hybrids, called Avatars.",
    trailer: "https://www.youtube.com/embed/TcMBFSGVi1c",
  },
  {
    id: "104",
    name: "127 Hours",
    pic: "https://m.media-amazon.com/images/M/MV5BMTc2NjMzOTE3Ml5BMl5BanBnXkFtZTcwMDE0OTc5Mw@@._V1_.jpg",
    rating: "7.5",
    des: "Aron Ralston, a mountain climber, is on a hiking adventure in Utah when he gets trapped in a canyon. Soon, he takes desperate measures to survive and struggles for 127 hours before he is rescued.",
    trailer: "https://www.youtube.com/embed/OlhLOWTnVoQ",
  },
  {
    id: "105",
    name: "Master",
    pic: "https://m.media-amazon.com/images/M/MV5BYWQxODNlMjktNjU3Yi00OTFmLTgyOTgtZDVhNDY5NzMwMmYwXkEyXkFqcGdeQXVyMTIwNjE1MTk0._V1_.jpg",
    des: "An alcoholic professor is sent to a juvenile school, where he clashes with a gangster who uses the school children for criminal activities.",
    rating: "8.1",
    trailer: "https://www.youtube.com/embed/UTiXQcrLlv4",
  },
];
